FROM python

COPY . /src/

WORKDIR /src/

RUN pip install -r requirements.txt

ENV DEBIAN_FRONTEND=noninteractive

# Install supervisor to change the `init` process
RUN apt update && apt -y install supervisor
# Install MariaDB
RUN apt -y install mariadb-server

RUN chmod +x /src/*.sh
RUN /src/dbsetup.sh
CMD supervisord -c /src/supervisord.conf
